### ISSUE TITLE
The newest game converted to NSP can‘t be recognized by goldleaf，like the witcher 3.

### ISSUE THREAD

**Issue by wzcnly** [The-4n/4NXCI#43]
The Witcher 3.XCI flie size is 23.9 GB.when it converted to NSP，the file size became more than 10GB.Also this nsp file can‘t be recognized by goldleaf.

**Comment by DarkMatterCore** [comment]
It would be helpful if you could provide more information about your current setup (CFW version, Switch FW version, CFW patch set used, etc.) and a screenshot of the Goldleaf error.

**Comment by wzcnly** [comment]
CFW version is atmosphere 0.94,Switch FW version is 8.1~9.0.1.CFW patch newest used.The error code is  0X234q02,fs(2),invalid NCA(might mean missing sigpatches or too low firmware)(4517)
I presume the file is incomplete.The file zise is too small.
I use NSBuilder to convert this XCI flie,the nsp flie size is the same as XCI.And it can be recognized by goldleaf in the same setup.

**Comment by DarkMatterCore** [comment]
You may be missing FS patches in your CFW. If you using vanilla Atmosphère (`fusee-primary` payload), use [this](https://gbatemp.net/threads/i-heard-that-you-guys-need-some-sweet-patches-for-atmosphere.521164/) patchset. Otherwise, if you're using Hekate, use [this](https://github.com/Joonie86/hekate/releases/latest) one.

I don't think the base game NSP is incomplete. The XCI most likely includes an update for the game and/or DLCs.

**Comment by wzcnly** [comment]
I have found out why this happened.The hard disk space isn't enough to make nsp file.
